title: SchülerRaustausch Columbus - Dresden 2019
email: ~
description: >-
  This is the blog of a student exchange between Columbus/Ohio and Dresden in
  the fall of 2019.
baseurl: ""
url: "https://schuelerraustausch.github.io"
twitter_username: ~
github_username: ~

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Readme.md
